import { createApp } from "vue";
import "./style.css";
import AppVue from "./App.vue";
import router from "./router";
import i18n from "./i18n";
import store, { key } from "./store/store";
const app = createApp(AppVue);
app.use(i18n);
app.use(router);
app.use(store, key);
app.mount("#app");
